apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  labels:
    app: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      name: crud-app
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app
          image: yasozs/crud-app:aks
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb:27017"